raspberry_webserver/apps/filesys/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'filesys'
urlpatterns = [
    path('<int:dir_id>/makedir/', views.make_dir, name='make-dir'),
    path('<int:dir_id>/removedir/', views.remove_dir, name='remove-dir'),
    path('<int:dir_id>/uploadfile/', views.upload_file, name='upload-file'),
    path('<int:dir_id>/removefile/', views.remove_file, name='remove-file'),
    path('getfile/<int:file_id>/', views.get_file, name='get-file'),
    path('<int:dir_id>/', views.get_dir, name='get-dir'),
    path('', views.go_to_root, name='root'),
]

raspberry_webserver/apps/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register_request, name='register'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
]

raspberry_webserver/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls), # Django admin route
    path('panel/', include('apps.filesys.urls')), # Filesystem panel
    path('', include('apps.users.urls')), # Login and register
]

raspberry_webserver/apps/filesys/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

class Directory(models.Model):
    parent_dir = models.ForeignKey(
        'Directory', on_delete=models.CASCADE, blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    abs_path = models.CharField(max_length=1000, blank=True)

    def get_name(self):
        if self.abs_path == '/':
            return '/'
        else:
            return self.abs_path.split('/')[-1]

    def __str__(self):
        return self.abs_path


class File(models.Model):
    parent_dir = models.ForeignKey(Directory, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    abs_path = models.CharField(max_length=1000)
    file = models.FileField(upload_to='uploaded_files')

    def get_name(self):
        if self.abs_path == '/':
            return '/'
        else:
            return self.abs_path.split('/')[-1]

    def __str__(self):
        return self.abs_path

raspberry_webserver/apps/filesys/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db import models


class FileUploadForm(forms.Form):
    file_field = forms.FileField(
        required=True,
    )

raspberry_webserver/apps/filesys/views.py
from django.http.response import HttpResponseBadRequest, HttpResponseNotAllowed, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import get_user_model, login
from django.contrib.auth.decorators import login_required
from django.conf import settings
import os

from .models import Directory, File
from .forms import FileUploadForm


User = get_user_model()


def get_abs_path(abs_path: str, name: str):
    if abs_path == '/':
        return '/' + name
    else:
        return abs_path + '/' + name


# Checks whether NAME is unique inside CUR_DIR so it can be the name of a new file or directory.
def is_name_unique(request, cur_dir, name):
    files = File.objects.filter(owner=request.user, parent_dir=cur_dir)
    for file in files:
        if file.get_name() == name:
            return False
    dirs = Directory.objects.filter(owner=request.user, parent_dir=cur_dir)
    for dir in dirs:
        if dir.get_name() == name:
            return False
    return True


# Go to root directory
@login_required(login_url='/login/')
def go_to_root(request):
    root_dir = get_object_or_404(Directory, owner=request.user, abs_path='/')
    return redirect('filesys:get-dir', dir_id=root_dir.id)


# Go to Directory
@login_required(login_url='/login/')
def get_dir(request, dir_id):
    dir = get_object_or_404(Directory, pk=dir_id, owner=request.user)
    upload_file_form = FileUploadForm()

    return render(request, 'filesys/panel.html', {'directory': dir, 'upload_file_form': upload_file_form})


# Make directory
@login_required(login_url='/login/')
def make_dir(request, dir_id):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    cur_dir = get_object_or_404(Directory, pk=dir_id, owner=request.user)
    if not is_name_unique(request, cur_dir, request.POST['dir-name']):
        return HttpResponseBadRequest("Directory name is not unique.")

    new_dir_abs_path = get_abs_path(cur_dir.abs_path, request.POST['dir-name'])
    new_dir = Directory(parent_dir=cur_dir,
                        owner=request.user, abs_path=new_dir_abs_path)
    new_dir.save()

    return redirect('filesys:get-dir', dir_id=dir_id)


# Delete Directory
@login_required(login_url='/login/')
def remove_dir(request, dir_id):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    cur_dir = get_object_or_404(Directory, pk=dir_id, owner=request.user)
    dir_to_remove = get_object_or_404(
        Directory, pk=request.POST['dir-id'], owner=request.user, parent_dir=cur_dir)
    dir_to_remove.delete()

    return redirect('filesys:get-dir', dir_id=dir_id)


# Upload file
@login_required(login_url='/login/')
def upload_file(request, dir_id):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    uploaded_file = list(request.FILES.values())[0]
    cur_dir = get_object_or_404(Directory, pk=dir_id, owner=request.user)
    if not is_name_unique(request, cur_dir, uploaded_file.name):
        return HttpResponseBadRequest("File name is not unique.")
    new_file_abs_path = get_abs_path(cur_dir.abs_path, uploaded_file.name)
    new_file = File(parent_dir=cur_dir, owner=request.user,
                    abs_path=new_file_abs_path, file=uploaded_file)
    new_file.save()

    return redirect('filesys:get-dir', dir_id=dir_id)


# Delete file
@login_required(login_url='/login/')
def remove_file(request, dir_id):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    cur_dir = get_object_or_404(Directory, pk=dir_id, owner=request.user)
    file_to_remove = get_object_or_404(
        File, pk=request.POST['file-id'], owner=request.user, parent_dir=cur_dir)
    file_to_remove_path = './' + os.path.join(
        settings.MEDIA_ROOT, file_to_remove.file.name)
    os.remove(file_to_remove_path)
    file_to_remove.delete()

    return redirect('filesys:get-dir', dir_id=dir_id)


# Download file
@login_required(login_url='/login/')
def get_file(request, file_id):
    if request.method != 'GET':
        return HttpResponseNotAllowed(['GET'])

    file = get_object_or_404(File, pk=file_id, owner=request.user)
    file_path = os.path.join(settings.MEDIA_ROOT, file.file.name)
    with open(file_path, 'rb') as f:
        response = HttpResponse(
            f.read(), content_type="application/vnd.ms-excel")
        response['Content-Disposition'] = 'inline; filename=' + \
            os.path.basename(file_path)
        return response

raspberry_webserver/apps/filesys/templates/filesys/panel.html
{% load static %}

<!DOCTYPE html>
<html> 
<head style="background-color: lightcyan;">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body style="background-color: lightcyan;">
    <div style="background-color: #8ecae6; color: #023047;">
    <div class=row >
      <p class="col h3" style="padding-left: 25px;"> Hello {{ request.user.username }}</p>
      <a class="col h3 text-center"href="{% url 'users:logout' %}">Logout</a>
    </div>
    </div>
    <p class="h4 text-center"> cwd: {{ directory.abs_path }} </p>

    {% if directory.parent_dir %}
    <div class="h5" style="padding-left:20px;">
        <a href="{% url 'filesys:get-dir' directory.parent_dir.id %}">Go to parent directory</a>
    </div>
    {% endif %}

    <div class="row">
      <form class="form-group" style="padding:10px; padding-left: 25px;" action="{% url 'filesys:upload-file' directory.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="file_field">File name:</label>
        {{ upload_file_form.file_field }}
        <button type="submit" class="btn btn-primary">Upload</button>
      </form>

      <form class="form-group col" style="padding:10px; padding-left: 25px;" action="{% url 'filesys:make-dir' directory.id %}" method="POST">
        {% csrf_token %}
        <label for="dir-name">Directory name:</label>
        <input type="text" id="dir-name" name="dir-name">
	      <button type="submit" class="btn btn-primary">Make Directory</button>
      </form>

    </div>

    <div class="row" style="display: flex; flex-wrap: wrap;">
    <h1> </h1>
    <div style="background-color: #8ecae6; color: #023047;">
    <p class="h5 text-center"> Directories </p>
    </div>
    {% for dir in directory.directory_set.all %}
    <div class="col" style="padding-left:25px;">
        <img src="{% static 'filesys/images/folder.png' %}" width=80 height=80>
        <a href="{% url 'filesys:get-dir' dir.id %}">{{ dir.get_name }}</a>
        <form action="{% url 'filesys:remove-dir' directory.id %}" method="POST">
            {% csrf_token %}
            <input type="text" id="dir-id" name="dir-id" value="{{ dir.id }}" hidden>
	          <button type="submit" class="btn btn-primary">Remove</button>
        </form>
    </div>
    {% endfor %}
    </div>
    <div class="row" style="display: flex; flex-wrap: wrap;"> 
    <h1> </h1>
    <div style="background-color: #8ecae6; color: #023047;">
    <p class="h5 text-center"> files </p>
    </div>
    {% for file in directory.file_set.all %}
    <div class="col"style="padding-left:25px;">
        <img src="{% static 'filesys/images/file.png' %}" width=80 height=80>
        <a href="{% url 'filesys:get-file' file.id %}">{{ file.get_name }}</a>
        <form action="{% url 'filesys:remove-file' directory.id %}" method="POST">
            {% csrf_token %}
            <input type="text" id="file-id" name="file-id" value="{{ file.id }}" hidden>
            <button type="submit" class="btn btn-primary">Remove</button>
        </form>
    </div>
    {% endfor %}
    </div>
</body>

</html>